# This configuration should be fetched from Spring Cloud Config
# environment specific configuration

# This is for local development only, shall not use otherwise
# Database
jdbc:
  url: jdbc:postgresql://localhost:5432/postgres
  username: postgres
  password: 123
