# This configuration should be fetched from Spring Cloud Config
# environment specific configuration

# This is for local development only, shall not use otherwise
# Database
spring:
  flyway:
#    url: jdbc:h2:mem:h2db
    url: jdbc:h2:file:./h2db

  r2dbc:
#    url: r2dbc:h2:mem:///h2db
    url: r2dbc:h2:file:///./h2db
