# This configuration should be fetched from Spring Cloud Config
# environment specific configuration

# This is for local development only, shall not use otherwise
# Database
spring:
  r2dbc:
    url: r2dbc:postgresql://127.0.0.1:5432/postgres
    properties:
      schema: valstrax
    username: postgres
    password: 123
